config/routes.rb
PIC::Application.routes.draw do

  get "contact/index"

  get "about/index"

  get "home/index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :products, :manufacturers, :categories, :articles

  root :to => 'home#index'
	match 'about' => 'about#index'
	match 'contact' => 'contact#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :pdf
  attr_accessible :body, :published, :title, :pdf
	
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_many :products
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  attr_accessible :name, :website, :description, :logo
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_many :products
	
	validates :name, :website, :description, :presence => true
	validates_format_of :website, :with => URI::regexp(%w(http https))
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :picture
	has_attached_file :spec_sheet
  attr_accessible :category_id, :manufacturer_id, :model, :name, :picture, :description, :spec_sheet
  
 
  belongs_to :category
  belongs_to :manufacturer
  
  validates :name, :model, :category_id, :manufacturer_id, :presence => true
	
	validates_attachment :spec_sheet, 
		:content_type => { :content_type => "application/pdf" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	helper_method :sort_column, :sort_direction
  def index
		@articles = Article.order(sort_column + " " + sort_direction).page(params[:page]).per(5)
  end
	
	def show
		@article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
	end

private

  def sort_column
    Article.column_names.include?(params[:sort]) ? params[:sort] : "published"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.order(:name).page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  
  def index
    @manufacturers = Manufacturer.order(:name).page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @manufacturer = Manufacturer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manufacturer }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	helper_method :sort_column, :sort_direction
  # GET /products
  # GET /products.json
  
  def index
    @products = Product.includes(:manufacturer, :category).page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def is_active?(page_name)
			"active" if params[:controller] == page_name
	end
	
	def page_title
		"PIC Appalachia | " + controller_name.titleize
	end
	
	def sortable(column, title = nil)
		title ||= column.titleize
		direction = sort_direction == "asc" ? "desc" : "asc"
		link_to title, {:sort => column, :direction => direction}
	end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/articles/index.html.erb
<div class="span9">
	<h2>Articles &amp Press Releases</h2><br>

	<table class="table">
		<thead>
			<tr>
				<th><%= sortable "published", "Date" %></th>
				<th><%= sortable "title" %></th>
			</tr>
		</thead>
		<tbody>
		<% @articles.each do |article|  %>
			<tr>
				<td>
					<strong>
						<%= article.published.strftime("%B %d, %Y") %>
					</strong>
				</td>
				<td>
					<h3>
						<%= link_to article.title, article_path(article) %>
					</h3>
					<p>
						<%= truncate(article.body, :length => 250)%>
						<%= link_to " Read More", article_path(article) %>
					</p>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>
	<%= paginate @articles %>
</div>

app/views/articles/show.html.erb
<div class="span9">
	<h2><%= @article.title %></h2><br>
	<p><span class="label label-info">Published:</span> <%= @article.published.strftime("%B %d, %Y") %></p><br>
	<div class="well">
		<p><%= truncate(@article.body, :length => 800) %></p>
		<p class="centered"><a class="btn btn-primary" href="<%= @article.pdf.url %>">Read the Full Article (PDF)</a></p>
	</div>
</div>

app/views/categories/index.html.erb
<div class="span9">
	<h2>Browse Products by Category</h2><br>
	<table class="table table-striped table-condensed">
			<tbody>
			<% @categories.each do |category| %>
			<tr>
				<td><h3><%= link_to category.name, category_path(category)  %></h3></td>
			</tr>
			<% end %>
			</tbody>
	</table>
</div>

app/views/categories/show.html.erb
<div class="span9">
	<h2><%= link_to "Categories", categories_path %> > 
	<%= @category.name %></h2>

	<table class="table">
		<thead>
			<tr>
			<th>Name</th>
			<th>Manufacturer</th>
			<th>Model</th>
		</tr>
		</thead>
		<tbody>
		<% @category.products.each do |product| %>
		<tr>
			<td><%= product.name %></td>
			<td><a href="<%= manufacturer_path(product.manufacturer) %>"><%= product.manufacturer.name %></a></td>
			<td><%= product.model %></td>
			<td><a class="btn" href="<%= product_path(product) %>">View</button></td>
		</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/contact/index.html.erb
<div class="span9">
	<h2>Contact us at any of our locations.</h2>

	<div class="row">
		<div class="span3">
			<h3>Monessen, PA</h3>
			<ul class="unstyled">
				<li>210 Riverview Drive</li>
				<li>Monessen, PA</li>
				<li>USA 15062</li>
				<li><abbr title="Phone">P:</abbr> (724) 746-5870</li>
				<li><abbr title="Fax">F:</abbr> (724) 684-5097</li>
			</ul>
		</div>
		<div class="span3">
			<h3>Poca, WV</h3>
			<ul class="unstyled">
				<li>300-2 Jacobsen Drive</li>
				<li>Poca, WV</li>
				<li>USA 25159</li>
				<li><abbr title="Phone">P:</abbr> (724) 746-5870</li>
				<li><abbr title="Fax">F:</abbr> (724) 746-1225</li>
			</ul>
		</div>
		<div class="span3">
			<h3>Lawrence, PA</h3>
			<ul class="unstyled">
				<li>2 Park Drive</li>
				<li>P.O. Box 614</li>
				<li>Lawrence, PA</li>
				<li>USA 15055</li>
			</ul>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="span9">
	<h2>Welcome to Power Ignition &amp; Controls Appalachia.</h2>

	<p>Originally incorporated in November, 1974 as Power Ignition Consultants Ltd., our early mission was to provide consulting services to the oilpatch. In subsequent years PIC represented five major lines of industrial ignition, which substantially contributed to the growth of the company.</p>
	<p>As the need for a full-service industrial ignition company grew, PIC included a service department and manufacturing facilities, in addition to offering a variety of engine control products.</p>
	<p>In 1993 PIC teamed up with Frank W. Murphy Mfr. to become a master stocking distributor for the full line of control and instrumentation products. FW Murphy end devices such as L1200 level switches and VS2EX vibration switches are extremely common; however, the complete line includes a full complement of electronic, micro-processor based controllers such as the S1501 and TTD for total engine control.</p>
	<p>Spartan Controls acquired Power Ignition Controls on July 1, 2003, forming Power Ignition and Controls, a division of Spartan Controls. This new division provides a complete line-up of engine and compressor controls, instrumentation and ignition systems products.</p>
	<p>In September 2011, PIC Appalachia was formed to serve our customers in the Appalachia basin.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
	<link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="container"><!-- BEGIN MAIN CONTAINER -->

<header>
	<!-- BEGIN TOP SEARCH-BAR -->
	<div class = "navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
			
				<ul class="nav">
					<li class=" <%= is_active?("home") %>"><a href="<%= root_path %>">
						<i class="icon-home icon-white"></i> Home</a>
					</li>
					<li class="dropdown <%= is_active?("products") %>"><a  class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-shopping-cart icon-white"></i> Products
						<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Browse all", products_path %></li>
							<li><%= link_to "Browse by Manufacturer", manufacturers_path %></li>
							<li><%= link_to "Browse by Category", categories_path %></li>
						</ul>
					</li>
					<li class=" <%= is_active?("articles") %>"><a href="<%= articles_path %>">
						<i class="icon-inbox icon-white"></i> News</a>
					</li>
					<li class=" <%= is_active?("about") %>"><a href="<%= about_path %>">
						<i class="icon-info-sign icon-white"></i> About</a>
					</li>
					<li class=" <%= is_active?("contact") %>"><a href="<%= contact_path %>">
						<i class="icon-envelope icon-white"></i> Contact</a>
					</li>
				</ul>
				<form class="navbar-search pull-right">
					<i class="icon-search icon-white"></i>
					<input type="text" class="search-query span2" placeholder="Search">
				</form>
			</div>
		</div>
	</div>
	<!-- END TOP SEARCH-NAVIGATION -->
	
	<div class="title">
		<h1 class="jumbo">Power Ignition &amp; Controls Appalachia</h1>
	</div>
</header>

	<div class="row main">
		<!-- SIDE NAVIGATION -->
		<div class="span3">
			<div class="well" style="padding: 8px 0;">
				<ul class="nav nav-list">
				
					<li class="nav-header">Products by Manufacturer</li>
					<% for @man in Manufacturer.all.sample(7) %>
							<li class="center-link">
								<a href="<%= manufacturer_path(@man) %>"><%= truncate(@man.name, :length => 29) %></a>
							</li>
					<% end %>
					<%= link_to "See all Manufacturers »", manufacturers_path, :class=>"btn btn-mini" %>
					
					<li class="nav-header">Products by Category</li>
					<% for @cat in Category.all.sample(7) %>
					<li class="center-link">
						<a href="<%= category_path(@cat) %>"><%= truncate(@cat.name, :length => 29)  %></a>
					</li>
					<% end %>
					<%= link_to "See all Categories »", categories_path, :class=>"btn btn-mini" %>
				</ul>
			</div>
		</div>
		<!-- END SIDE NAVIGATION -->
		<%= yield %>
	</div>
</div><!-- END MAIN CONTAINER -->

	<footer class="footer">
		<div class="container">
			<div class="row">
			<div class="span8">
				<ul class="nav nav-pills">
					<li class=" <%= is_active?("home") %>"><a href="<%= root_path %>">
						Home</a>
					</li>
					<li class="dropup <%= is_active?("products") %>"><a  class="dropdown-toggle" data-toggle="dropdown" href="#">
					Products <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Browse all", products_path %></li>
							<li><%= link_to "Browse by Manufacturer", manufacturers_path %></li>
							<li><%= link_to "Browse by Category", categories_path %></li>
						</ul>
					</li>
					<li class=" <%= is_active?("articles") %>"><a href="<%= articles_path %>">News</a>
					</li>
					<li class=" <%= is_active?("about") %>"><a href="<%= about_path %>">About</a>
					</li>
					<li class=" <%= is_active?("contact") %>"><a href="<%= contact_path %>">Contact</a>
					</li>
				</ul>
			</div>
			<div class="span4">
				<h6 class="pull-right">Copyright &copy; PIC Appalachia, 2012.</h6>
				<h6 class="pull-right">All Rights Reserved.</h6>
			</div>
	</footer>
</body>
</html>

app/views/manufacturers/index.html.erb
<div class="span9">
	<h2>Browse Products by Manufacturer</h2><br>
	<table class="table">
			<tbody>
			<% @manufacturers.each do |manufacturer| %>
			<tr class="man-tr">
				<td>
					<% if manufacturer.logo.exists? %>
					<%= image_tag manufacturer.logo.url(:thumb) %>
					<% end %>
				</td>
				<td><h2><%= link_to manufacturer.name, manufacturer_path(manufacturer)  %></h2></td>
			</tr>
			<% end %>
			</tbody>
	</table>
</div>

app/views/manufacturers/show.html.erb
<div class="span9">
	<h2><%= link_to "Manufacturers", manufacturers_path %> > 
	<%= @manufacturer.name %></h2>

	<table class="table">
		<thead>
			<tr>
			<th>Name</th>
			<th>Category</th>
			<th>Model</th>
		</tr>
		</thead>
		<tbody>
		<% @manufacturer.products.each do |product| %>
		<tr>
			<td><%= product.name %></td>
			<td><a href="<%= category_path(product.category) %>"><%= product.category.name %></a></td>
			<td><%= product.model %></td>
			<td><a class="btn" href="<%= product_path(product) %>">View</a></td>
		</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/products/index.html.erb
<div class="span9">
	<h2>All Products</h2>

	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th>Name</th>
				<th class="model-row">Model</th>
				<th>Category</th>
				<th>Manufacturer</th>
			</tr>
		</thead>
		<tbody>
		<% @products.each do |product| %>
		<tr>
			<td><%= product.name %></td>
			<td><code><%= product.model %></code></td>
			<td><a href="<%= category_path(product.category) %>"><%= product.category.name %></a></td>
			<td><a href="<%= manufacturer_path(product.manufacturer) %>"><%= product.manufacturer.name %></a></td>
			<td><a  class="btn" href="<%= product_path(product) %>">View</a></td>
		</tr>
		<% end %>
		</tbody>
	</table>

	<%= paginate @products %>
</div>

app/views/products/show.html.erb
<div class="span9">
	<h2><a href="<%= products_path %>">Products</a> > <%= @product.name %></h2>
	<div class="span4 pull-right prod-img">
		<% if !@product.picture? %>
			<p class="well"><em>Picture Not Available</em></p>
		<% else %>
			<a class="thumbnail" href="<%= @product.picture.url %>"><%= image_tag @product.picture.url %></a>
		<% end %>
	</div>
	
	<p><%= @product.description %></p>
	
	<table class="table prod-descr">
		<tr>
			<th>Model</th>
			<td><code><%= @product.model %></code></td>
		<tr>
			<th>Category</th>
		<td><%= @product.category.name %></td>
		</tr>
		<tr>
			<th>Manufacturer</th>
		<td><%= @product.manufacturer.name %></td>
		</tr>
		<% if @product.spec_sheet.exists? %>
		<tr>
			<th>Specifications</th>
		<td><a class="btn btn-primary" href="<%= @product.spec_sheet.url %>">Spec Sheet (PDF)</a></td>
		</tr>
		<% end %>
	</table>
</div>